function dYdx = MOL_deriv(x,Y)

% Finite difference paramters
global xi_step
% Diffusion paramters
global Sigma_m Sigma_l D_c; 
% Chemotaxis force 
global k;
% Growth/death parameters
global d_a chi_l ;
%Boundary condition parameters 
global h_l h_n h_a l_inf n_inf a_inf; 

% Offsets for ODE matrix
% Batting order: l, m, c, a, R
l = 0*(1/xi_step + 1);
m = 1*(1/xi_step + 1);
c = 2*(1/xi_step + 1);
a = 3*(1/xi_step + 1);
R = 4*(1/xi_step + 1) + 1;

xi_value = linspace(0,1,1/xi_step + 1);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%       Ghost Points         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Temporarily set i to its value on the boundary
i = 1/xi_step + 1;

%checked - OK
m_ghostPoint = Y(m + i - 1) + Y(R)*2*xi_step*(...
                    (k*h_n*(n_inf + Y(m + i) + Y(l + i) - 1))/ ...
                    (Sigma_m*(Y(l + i) + (1 - Y(l + i))*(1 - 1/Y(m + i))))...
               );

%checked - OK
a_ghostPoint = Y(a + i - 1) + Y(R)*2*xi_step*(...
                    h_a*(a_inf - Y(a + i))...
               );

%checked - OK
l_ghostPoint = Y(l + i - 1) + ((Y(l + i)*Y(R)*2*xi_step)/Sigma_l)*(...
                    chi_l/Y(R)*((a_ghostPoint - Y(a + i - 1))/(2*xi_step)) + ...
                    1/(Y(m + i)*Y(R))*(k*h_n*(n_inf + Y(m + i) + Y(l + i) - 1))/(Y(l + i) + (1 - Y(l + i))*(1 - 1/Y(m + i)))...
               ) + ...
               (Y(R)*2*xi_step)/Sigma_l*h_l*k*(l_inf - Y(l + i));

%checked - OK
DRdt = (1/(k*Y(R)))*(...
            Sigma_m*(m_ghostPoint - Y(m + i - 1 ))/(2*xi_step) + ...
            Sigma_l*(l_ghostPoint - Y(l + i - 1 ))/(2*xi_step) - ...
            1/(Y(m + i))*Sigma_m*(m_ghostPoint - Y(m + i - 1))/(2*xi_step) - ...
            chi_l*Y(l + i)*(a_ghostPoint - Y(a + i - 1))/(2*xi_step) );
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%   Xi = 0 BC (Zero Flux)    %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = 1;

% l (Macrophages)
%checked - OK
dYdx(l + i, 1) = (6/(xi_step^2*Y(R)^2))*(...
                    Sigma_l*(1 - Y(l + i))/k*(Y(l + i + 1) - Y(l + i))...
                 ) - ...
                 Y(l + i)*fun_d_l(Y(c + i));

% m (Tumour Cells)
%checked - OK
dYdx(m + i, 1) = (6/(xi_step^2*Y(R)^2))*(...
                    Sigma_m*(1 - Y(m + i))/k*(Y(m + i + 1) - Y(m + i))...
                 ) - ...
                 + Y(m + i)*fun_p_m_fix( Y(m + i), Y(c + i) ) - Y(m + i)*fun_d_m(Y(c + i)) - Y(l + i)*Y(m+i)*fun_k(Y(c+i));

%c (Oxygen)
%checked - OK
dYdx(i + c,1) = (6/(xi_step^2*Y(R)^2))*(...
                    D_c*(Y(c + i + 1) - Y(c + i))...
                ) - fun_d_c( Y(m + i), Y(l + i), 1-Y(m + i)-Y(l + i),Y(c + i));
         

% a (Chemoattractant)
%checked - OK
dYdx(i + a, 1) = (6/(xi_step^2*Y(R)^2))*(...
                    (Y(a + i + 1) - Y(a + i))...
                 ) + d_a*(fun_p_a(Y(l + i),Y(m + i),Y(c + i)) - Y(a + i));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%   Xi in (0,1) [Interior]   %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for i = 2:1/xi_step 
    
    % l (Macrophages)
    %checked - OK
    dYdx(i + l, 1) = (xi_value(i)/Y(R))*DRdt*(Y(l + i + 1) - Y(l + i - 1))/(2*xi_step)  + ...
                     (1/(k*Y(R)^2))*(...
                        (2/xi_value(i))*(...
                            Sigma_l*(Y(l + i + 1) - Y(l + i -1))/(2*xi_step) - chi_l*((1 - Y(l + i)))*Y(l + i)*(Y(a + i + 1) - Y(a + i -1))/(2*xi_step) - Y(l + i)*(Sigma_m*(Y(m + i + 1) - Y(m + i - 1))/(2*xi_step) + Sigma_l*(Y(l + i + 1) - Y(l + i - 1))/(2*xi_step))...
                        ) + ...
                        (Sigma_l)*(Y(l + i + 1) - 2*Y(l + i) + Y(l + i - 1))/(xi_step^2) - chi_l*((Y(i + l + 1) - Y(i + l - 1))/(2*xi_step) - 2*Y(l + i)*(Y(l + i + 1) - Y(l + i - 1))/(2*xi_step))*((Y(a + i + 1) - Y(a + i - 1))/(2*xi_step)) - ...
                        chi_l*((1 - Y(l + i)))*Y(l + i)*(Y(a + i + 1) - 2*Y(a + i) + Y(a + i -1))/(xi_step^2) - ((Y(l + i + 1) - Y(l + i - 1))/(2*xi_step))*(Sigma_m*(Y(m + i + 1) - Y(m + i - 1))/(2*xi_step) + Sigma_l*(Y(l + i + 1) - Y(l + i - 1))/(2*xi_step)) - ...
                        Y(l + i)*(Sigma_l*(Y(l + i + 1) - 2*Y(l + i) + Y(l + i - 1))/(xi_step^2) + Sigma_m*(Y(m + i + 1) - 2*Y(m + i) + Y(m + i - 1))/(xi_step^2))...
                     ) - Y(l + i)*fun_d_l(Y(c + i));
    
                 
                 
    % m (Tumour Cells)
    %checked - OK
    dYdx(i + m, 1) = (xi_value(i)/Y(R))*DRdt*(Y(m + i + 1) - Y(m + i - 1))/(2*xi_step) + ...
                     (1/(k*Y(R)^2))*(...
                        (2/xi_value(i))*(...
                            Sigma_m*(Y(m + i + 1) - Y(m + i - 1))/(2*xi_step) + chi_l*Y(m + i)*Y(l + i)*(Y(a + i + 1) - Y(a + i - 1))/(2*xi_step) - Y(m + i)*(Sigma_m*(Y(m + i + 1) - Y(m + i - 1))/(2*xi_step) + Sigma_l*(Y(l + i + 1) - Y(l + i - 1))/(2*xi_step))...
                        ) + ...
                        Sigma_m*(Y(m + i + 1) - 2*Y(m + i) + Y(m + i - 1))/(xi_step^2) + chi_l*(Y(a + i + 1) - 2*Y(a + i) + Y(a + i - 1))/(xi_step^2)*Y(m + i)*Y(l + i) + ...
                        chi_l*(Y(a + i + 1) - Y(a + i - 1))/(2*xi_step)*((Y(m + i + 1) - Y(m + i - 1))/(2*xi_step)*Y(l + i) + Y(m + i)*(Y(l + i + 1) - Y(l + i - 1))/(2*xi_step)) - ...
                        (Y(m + i + 1) - Y(m + i - 1))/(2*xi_step)*(Sigma_m*(Y(m + i + 1) - Y(m + i - 1))/(2*xi_step) + Sigma_l*(Y(l + i + 1) - Y(l + i - 1))/(2*xi_step)) - ...
                        Y(m + i)*(Sigma_m*(Y(m + i + 1) - 2*Y(m + i) + Y(m + i - 1))/(xi_step^2) + Sigma_l*(Y(l + i + 1) - 2*Y(l + i) + Y(l + i - 1))/(xi_step^2))...
                        ) + Y(m + i)*fun_p_m_fix( Y(m + i), Y(c + i) ) - Y(m + i)*fun_d_m( Y(c + i) ) - Y(l + i)*Y(m + i)*fun_k(Y(c + i));
    
    
 
    %c (Oxygen)
    %checked - OK
    dYdx(i + c,1) = (xi_value(i)/Y(R))*DRdt*(Y(c + i + 1) - Y(c + i - 1))/(2*xi_step) + ...
                    (D_c/Y(R)^2)*(...
                        (2/xi_value(i))*(Y(c + i + 1) - Y(c + i - 1))/(2*xi_step) + ...
                        (Y(c + i + 1) - 2*Y(c + i) + Y(c + i - 1))/(xi_step^2)...
                    ) - fun_d_c( Y(m + i), Y(l + i), 1-Y(m + i)-Y(l + i),Y(c + i));
    
    
    
    % a (Chemoattractant)
    %checked - OK
    dYdx(i + a, 1) = (xi_value(i)/Y(R))*DRdt*(Y(a + i + 1) - Y(a + i - 1))/(2*xi_step) + ...
                    (1/Y(R)^2)*(...
                        (2/xi_value(i))*(Y(a + i + 1) - Y(a + i - 1))/(2*xi_step) + ...
                        (Y(a + i + 1) - 2*Y(a + i) + Y(a + i - 1))/(xi_step^2)...
                    ) + d_a*(fun_p_a(Y(l + i),Y(m + i),Y(c + i)) - Y(a + i));
      
                
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%      Xi = 1 BC and R       %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i + 1;

% l
%checked - OK
dYdx(i + l, 1) = (xi_value(i)/Y(R))*DRdt*(l_ghostPoint - Y(l + i - 1))/(2*xi_step)  + ...
                     (1/Y(R)^2)*(...
                        (2/(k*xi_value(i)))*(...
                            Sigma_l*(l_ghostPoint - Y(l + i -1))/(2*xi_step) - chi_l*(1 - Y(l + i))*Y(l + i)*(a_ghostPoint - Y(a + i - 1))/(2*xi_step) - Y(l + i)*(Sigma_m*(m_ghostPoint - Y(m + i - 1))/(2*xi_step) + Sigma_l*(l_ghostPoint - Y(l + i - 1))/(2*xi_step))...
                        ) + ...
                        Sigma_l*(l_ghostPoint - 2*Y(l + i) + Y(l + i - 1))/(xi_step^2) - chi_l*((l_ghostPoint - Y(i + l - 1))/(2*xi_step) - 2*Y(l + i)*(l_ghostPoint - Y(l + i - 1))/(2*xi_step))*((a_ghostPoint - Y(a + i - 1))/(2*xi_step)) - ...
                        chi_l*((1 - Y(l + i)))*Y(l + i)*(a_ghostPoint - 2*Y(a + i) + Y(a + i -1))/(xi_step^2) - ((l_ghostPoint - Y(l + i - 1))/(2*xi_step))*(Sigma_m*(m_ghostPoint - Y(m + i - 1))/(2*xi_step) + Sigma_l*(l_ghostPoint - Y(l + i - 1))/(2*xi_step)) - ...
                        Y(l + i)*(Sigma_l*(l_ghostPoint - 2*Y(l + i) + Y(l + i - 1))/(xi_step^2) + Sigma_m*(m_ghostPoint - 2*Y(m + i) + Y(m + i - 1))/(xi_step^2))...
                     ) - Y(l + i)*fun_d_l(Y(c + i));
          
% m
%checked - OK
dYdx(i + m, 1) = (xi_value(i)/Y(R))*DRdt*(m_ghostPoint - Y(m + i - 1))/(2*xi_step) + ...
                     (1/Y(R)^2)*(...
                        (2/xi_value(i))*(...
                            (Sigma_m/k)*(m_ghostPoint - Y(m + i - 1))/(2*xi_step) + chi_l*(Y(m + i)/k)*Y(l + i)*(a_ghostPoint - Y(a + i - 1))/(2*xi_step) - (Y(m + i)/k)*(Sigma_m*(m_ghostPoint - Y(m + i - 1))/(2*xi_step) + Sigma_l*(l_ghostPoint - Y(l + i - 1))/(2*xi_step))...
                        ) + ...
                        (Sigma_m/k)*(m_ghostPoint - 2*Y(m + i) + Y(m + i - 1))/(xi_step^2) + chi_l*(a_ghostPoint - 2*Y(a + i) + Y(a + i - 1))/(xi_step^2)*((Y(m + i)*Y(l + i))/k) + ...
                        chi_l*(a_ghostPoint - Y(a + i - 1))/(2*xi_step)*((1/k)*(m_ghostPoint - Y(m + i - 1))/(2*xi_step)*Y(l + i) + (1/k)*Y(m + i)*(l_ghostPoint - Y(l + i - 1))/(2*xi_step)) - ...
                        (1/k)*(m_ghostPoint - Y(m + i - 1))/(2*xi_step)*(Sigma_m*(m_ghostPoint - Y(m + i - 1))/(2*xi_step) + Sigma_l*(l_ghostPoint - Y(l + i - 1))/(2*xi_step)) - ...
                        (Y(m + i)/k)*(Sigma_m*(m_ghostPoint - 2*Y(m + i) + Y(m + i - 1))/(xi_step^2) + Sigma_l*(l_ghostPoint - 2*Y(l + i) + Y(l + i - 1))/(xi_step^2))...
                        ) + Y(m + i)*fun_p_m_fix( Y(m + i), Y(c + i) ) - Y(m + i)*fun_d_m( Y(c + i) ) - Y(l + i)*Y(m + i)*fun_k(Y(c + i));
    
%c
%checked - OK
dYdx(i + c,1) = 1 - Y(c + i);
    
% a
%checked - OK
dYdx(i + a, 1) = (xi_value(i)/Y(R))*DRdt*(a_ghostPoint - Y(a + i - 1))/(2*xi_step) + ...
                    (1/Y(R)^2)*(...
                        (2/xi_value(i))*(a_ghostPoint - Y(a + i - 1))/(2*xi_step) + ...
                        (a_ghostPoint - 2*Y(a + i) + Y(a + i - 1))/(xi_step^2)...
                    ) + d_a*(fun_p_a(Y(l + i),Y(m + i),Y(c + i)) - Y(a + i));
         
% R
%checked - OK
dYdx(R,1) = DRdt;

end